export enum EServiceErrorStatus {
  ERR_NOT_FOUND = 'ERR_NOT_FOUND',
  ERR_CONFLICT = 'ERR_CONFLICT',
  ERR_ACCESS_FORBIDDEN = 'ERR_ACCESS_FORBIDDEN',
  ERR_BAD_INPUT_DATA = 'ERR_BAD_INPUT_DATA',
  ERR_UNKNOWN = 'ERR_UNKNOWN',
  ERR_UNPROCESSABLE_ENTITY = 'ERR_UNPROCESSABLE_ENTITY',
}
